name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Install luacheck
      run: sudo apt-get update && sudo apt-get install -y lua-check

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run luacheck
      run: luacheck . --exclude-files ./Libs