name: Release

on:
  push: { tags: ['v*'] }

jobs:
  publish:
    name: Create release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Package
      env:
        GITHUB_REPONAME: ${{ github.event.repository.name }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        pushd "$GITHUB_WORKSPACE/.."
        zip -r "$HOME/$GITHUB_REPONAME-${GITHUB_REF#refs/*/}.zip" "$GITHUB_REPONAME" -x "$GITHUB_REPONAME/.*"
        popd

    - name: Read changelog
      id: read-changelog
      uses: mindsers/changelog-reader-action@v2

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        name: Release ${{ steps.read-changelog.outputs.version }}
        artifactErrorsFailBuild: true
        artifacts: ~/${{ github.event.repository.name }}-*.zip
        body: ${{ steps.read-changelog.outputs.changes }}
        token: ${{ secrets.GITHUB_TOKEN }}